module.exports = [
  {
    id: 1,
    stateContracts: [
      'California Department of Mental Health',
      'Nevada Department of Mental Health',
      'Utah Department of Mental Health',
      'Wyoming Mental Health Division',
      'Wyoming Substance Abuse Division',
      'Washington Department of Social and Health Services',
    ],
    countyContracts: [
      'Alpine County Behavioral Health Services',
      'Butte County Department of Employment and Social Services',
      'Butte County Behavioral Health Services',
      'Colusa County Health and Human Services',
      'Del Norte County Behavioral Health Services',
      'Fresno County Behavioral Health Services',
      'Glenn County Health and Human Services',
      'Glenn County Behavioral Health Services',
      'Inyo County Behavioral Health Services',
      'Lake County Behavioral Health Services',
      'Mariposa County Behavioral Health Services',
      'Mendocino County Behavioral Health Services',
      'Nevada County Behavioral Health Services',
      'Placer County Health and Human Services',
      'Sacremento County Behavioral Health Services',
      'San Benito County Behavioral Health Services',
      'Tehama County Behavioral Health Services',
      'Trinity County Behavioral Health Services',
      'Yolo County Behavioral Health Services',
    ],
    updatedAt: '2017-11-19T17:25:28.445Z',
    createdAt: '2017-11-19T17:25:28.445Z',
  },
];
